### PR TITLE
sanger config

### PR DESCRIPTION
**Pull request by priyanka-surana**
Add `sanger.config`

Also review the 6 wiki pages  - https://github.com/sanger-tol/nf-core-pipeline/wiki

This will close JIRA ticket https://jira.sanger.ac.uk/browse/TOLIT-559

The `Home` will be completed after some pages are transferred from Confluence.

### CODE REVIEW

**Comment by muffato** [comment]
- `nextflow.config`
   There is more stuff than listed under "What not to change?" and "What to change?", like the `check_max` function, etc. I would suggest to change the paragraph to:
   > Only change: "Input options" and "Max resource options" in `params`, and `manifest`
   
   and then mention the nextflow version, etc
- `conf/sanger.config`
   Having a copy of this file in every pipeline seems to go against the nf-core preferred setup. Can we upload our config to nf-core/configs instead ?
- `conf/base.config`
    `process_single` is a better name than `process_nompi` (not all multi-threaded software use MPI), and `process_single` is what's now used in nf-core.
    These two labels need a one-line description

**Comment by priyanka-surana** [comment]
We **do not** change max resource options in `nextflow.config`

**Comment by muffato** [comment]
right. even simpler :)

**Comment by priyanka-surana** [comment]
We had some conversation about `conf/sanger.config` on the nextflow email list but then it dropped again. I can submit a PR and post the link to `sanger-openstack#workflow-systems`. If approved, we can load with `-profile sanger`.

**Comment by priyanka-surana** [comment]
Updated the config wiki page

**Comment by priyanka-surana** [comment]
https://github.com/nf-core/configs/pull/399

**Comment by priyanka-surana** [comment]
I am closing this ticket since we don't want to merge this anymore. Its been uploaded to [`nf-core/configs`](https://github.com/nf-core/configs/blob/master/conf/sanger.config) and the Wiki has been updated accordingly.

**Pull request closed without merging**
