### PR TITLE
New subworkflows for preparing Fasta files

### PR DESCRIPTION
**Pull request by muffato**
cf TOLIT-702

There are two subworkflows: one for all Fasta files, and one specifically for repeat-masked files. Both have a README, a config file for testing, a demo workflow, and the actual subworkflow.

Example outputs:
```
$ nextflow run src/nf-core-pipeline/subworkflows/prepare_fasta/main.nf --fasta GCA_927399515.1.fa --outdir test_dir1
N E X T F L O W  ~  version 22.04.0
Launching `src/nf-core-pipeline/subworkflows/prepare_fasta/main.nf` [golden_swirles] DSL2 - revision: c5598b1304
executor >  local (3)
[2a/5d9881] process > PREPARE_FASTA:TABIX_BGZIP (GCA_927399515.1)                [100%] 1 of 1 ✔
[31/08bd84] process > PREPARE_FASTA:CUSTOM_GETCHROMSIZES (GCA_927399515.1.fa.gz) [100%] 1 of 1 ✔
[9b/f8757a] process > PREPARE_FASTA:SAMTOOLS_DICT (GCA_927399515.1.fa)           [100%] 1 of 1 ✔

$ tree test_dir1/
test_dir1/
├── GCA_927399515.1.fa.dict
├── GCA_927399515.1.fa.gz
├── GCA_927399515.1.fa.gz.fai
├── GCA_927399515.1.fa.gz.gzi
└── GCA_927399515.1.fa.gz.sizes
```
and
```
$ nextflow run src/nf-core-pipeline/subworkflows/prepare_repeat_masked_fasta/main.nf --fasta GCA_927399515.1.masked.ncbi.fa --outdir test_dir2
N E X T F L O W  ~  version 22.04.0
Launching `src/nf-core-pipeline/subworkflows/prepare_repeat_masked_fasta/main.nf` [lonely_boyd] DSL2 - revision: 301caee5ef
executor >  local (7)
[5f/7b3862] process > PREPARE_REPEAT_MASKED_FASTA:MASKING_TO_BED (GCA_927399515.1.masked.ncbi.fa)          [100%] 1 of 1 ✔
[84/b6cf80] process > PREPARE_REPEAT_MASKED_FASTA:TABIX_BGZIP_BED (GCA_927399515.1.masked.ncbi)            [100%] 1 of 1 ✔
[8d/8b2ab6] process > PREPARE_REPEAT_MASKED_FASTA:TABIX_TABIX_CSI (GCA_927399515.1.masked.ncbi)            [100%] 1 of 1 ✔
[47/158a8a] process > PREPARE_REPEAT_MASKED_FASTA:TABIX_TABIX_TBI (GCA_927399515.1.masked.ncbi)            [100%] 1 of 1 ✔
[72/b30679] process > PREPARE_REPEAT_MASKED_FASTA:TABIX_BGZIP_FASTA (GCA_927399515.1.masked.ncbi)          [100%] 1 of 1 ✔
[1b/235fd2] process > PREPARE_REPEAT_MASKED_FASTA:CUSTOM_GETCHROMSIZES (GCA_927399515.1.masked.ncbi.fa.gz) [100%] 1 of 1 ✔
[f1/6db403] process > PREPARE_REPEAT_MASKED_FASTA:SAMTOOLS_DICT (GCA_927399515.1.masked.ncbi.fa)           [100%] 1 of 1 ✔
$ tree test_dir2
test_dir2
├── GCA_927399515.1.masked.ncbi.bed
├── GCA_927399515.1.masked.ncbi.bed.gz
├── GCA_927399515.1.masked.ncbi.bed.gz.csi
├── GCA_927399515.1.masked.ncbi.bed.gz.tbi
├── GCA_927399515.1.masked.ncbi.fa.dict
├── GCA_927399515.1.masked.ncbi.fa.gz
├── GCA_927399515.1.masked.ncbi.fa.gz.fai
├── GCA_927399515.1.masked.ncbi.fa.gz.gzi
└── GCA_927399515.1.masked.ncbi.fa.gz.sizes
```
(typically the `.bed` wouldn't be published)

Initially they had a few differences (https://github.com/sanger-tol/insdcdownload/blob/main/subworkflows/local/prepare_genome.nf vs https://github.com/sanger-tol/insdcdownload/blob/main/subworkflows/local/prepare_repeats.nf ) but after a round of polishing, `prepare_repeat_masked_fasta` is essentially the same as `prepare_fasta` with additional modules to extract the BED file and index it.
I guess this means I could make `prepare_repeat_masked_fasta` call `prepare_fasta` ? That would make the installation instructions slightly more complex, and would introduce another depth of subworkflows (is that an issue ?)
Another idea might be to have a single workflow that always extracts the BED file, but then only indexes it if it's not empty ? There would be extra compute cost parsing the Fasta file, though.

### CODE REVIEW

**Comment by priyanka-surana** [comment]
You can call another subworkflow from within a subworkflow, it doesn't cause any problems. I do this in readmapping without issue.

**Comment by priyanka-surana** [comment]
@muffato Do you want to modify the structure before I review?

**Comment by muffato** [comment]
@priyanka-surana . Done. I've copied `prepare_fasta` into the `prepare_repeat_masked_fasta` subworkflow.
(I've left `masking_to_bed` as it is because I couldn't find any satisfying 2-word name)

**Comment by priyanka-surana** [comment]
Why do you need both subworkflows? Since `prepare_fasta` is being called from inside `prepare_repeat_masked_fasta`, maybe just combine the `README` and instructions. If someone wants just one, they can always piece it apart easily. 

Suggestion on `masking_to_bed`: `repeats_bed.nf` since it creates a bed file for repeats, which are the masked regions.

Also consider shortening the name of `prepare_repeat_masked_fasta`, suggestion `prepare_repeats` since all the genome work is done in `prepare_fasta` and this adds additional repeat associated functionality. You can also rename `prepare_fasta` to `prepare_genome` to be more specific.

**Comment by muffato** [comment]
OK. I would do this:
- rename `masking_to_bed` to `repeats_bed`
- rename `prepare_repeat_masked_fasta` to `prepare_repeats` and remove the call to `prepare_fasta` from it, i.e. make it a subworkflow that only deals with the BED file. I'd prefer pipeline developers to take _2_ subworkflows and be able to use these without modifications, rather than having just 1 subworkflow that needs to be edited.

**Comment by muffato** [comment]
Done
```
$ nextflow run src/nf-core-pipeline/subworkflows/prepare_repeats/main.nf --fasta GCA_927399515.1.masked.ncbi.fa --outdir test_dir3
N E X T F L O W  ~  version 22.04.0
Launching `src/nf-core-pipeline/subworkflows/prepare_repeats/main.nf` [goofy_wilson] DSL2 - revision: b8a11b23d7
executor >  local (4)
[c7/460cbf] process > PREPARE_REPEATS:REPEATS_BED (GCA_927399515.1.masked.ncbi.fa)  [100%] 1 of 1 ✔
[da/e2dd3f] process > PREPARE_REPEATS:TABIX_BGZIP (GCA_927399515.1.masked.ncbi)     [100%] 1 of 1 ✔
[d2/33626e] process > PREPARE_REPEATS:TABIX_TABIX_CSI (GCA_927399515.1.masked.ncbi) [100%] 1 of 1 ✔
[d2/5c1a7c] process > PREPARE_REPEATS:TABIX_TABIX_TBI (GCA_927399515.1.masked.ncbi) [100%] 1 of 1 ✔

$ tree test_dir3/
test_dir3/
├── GCA_927399515.1.masked.ncbi.bed
├── GCA_927399515.1.masked.ncbi.bed.gz
├── GCA_927399515.1.masked.ncbi.bed.gz.csi
└── GCA_927399515.1.masked.ncbi.bed.gz.tbi

```

**Review by priyanka-surana — APPROVED** [review]

**Comment by muffato** [comment]
Thank you ! Next PR will be making sanger-tol/insdcdownload use these subworkflows

**Pull request merged**
